# GitHub Labels for hushh-labs/consent-protocol
# Apply with: gh label create <name> --color <color> --description <description>

- name: agent
  color: "7057ff"
  description: "Related to agent implementations"

- name: operon
  color: "0e8a16"
  description: "Related to operon business logic"

- name: service
  color: "1d76db"
  description: "Related to database service layer"

- name: consent
  color: "d93f0b"
  description: "Related to consent token system"

- name: breaking
  color: "b60205"
  description: "Breaking change (new scopes, token format, DB migration)"

- name: docs
  color: "0075ca"
  description: "Documentation only"

- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: enhancement
  color: "a2eeef"
  description: "New feature or request"

- name: proposal
  color: "fbca04"
  description: "Design proposal requiring discussion"

- name: security
  color: "ee0701"
  description: "Security-related issue"

- name: mcp
  color: "5319e7"
  description: "Related to MCP server integration"

- name: kai
  color: "006b75"
  description: "Related to Agent Kai financial analysis"
